package org.thisisthepy.python.multiplatform.tcl

import kotlinx.coroutines.runBlocking
import org.thisisthepy.python.multiplatform.packpack.dependency.backend.BackendInterface
import org.thisisthepy.python.multiplatform.packpack.dependency.backend.BackendType
import java.io.File

private const val PYPROJECT_FILE = "pyproject.toml"

/**
 * Finds the `pypackpack`/`uv` project root by walking up from [startDir] looking for a
 * `pyproject.toml` -- mirrors `pypackpack`'s own `findProjectRoot`
 * (`packpack/utils/Workspace.kt`), reimplemented here rather than reused because that function is
 * `internal` to the `packpack` Gradle module and is not part of its published API surface.
 */
fun findProjectRoot(startDir: File): File? {
    var current: File? = startDir.canonicalFile
    while (current != null) {
        if (File(current, PYPROJECT_FILE).isFile) return current
        current = current.parentFile
    }
    return null
}

/**
 * `tcl install <package>` -- the one command from GitHub issue thisisthepy/toolchain#1
 * ("toolchain-lite") this module makes real end to end.
 *
 * `pypackpack` already has every piece this needs (`docs/SPEC.md` "Project creation", "Dev
 * environment dependency management"): `pypackpack init` and `pypackpack add <name>`. What a
 * python-only user coming from `pip install`/`npm install` is missing is the two-step dance of
 * running `init` first if nothing exists yet, then `add`. [install] collapses both into the one
 * call the issue's usage example shows.
 *
 * Deliberately calls `dependency.backend.BackendInterface` directly -- the same layer
 * `:toolchain-gradle-plugin`'s `InstallDependenciesTask.installWithPackpack` uses -- rather than the
 * `dependency.frontend`/`middleware` layers `pypackpack`'s own CLI is built on. Those resolve the
 * project root from the JVM-global `user.dir` system property (`pypackpack`'s internal
 * `findProjectRoot()`); the backend layer takes `workingDir: File?` as an explicit parameter
 * instead, which is what lets [install] and its tests pass a temp directory directly instead of
 * mutating global JVM state.
 */
class Installer(
    private val backend: BackendInterface = BackendInterface.create(BackendType.UV),
) {
    /**
     * Adds [packageName] as a dependency of the project rooted at (or above) [workingDir],
     * initializing a fresh `pyproject.toml` there first via `uv init --bare` if [findProjectRoot]
     * finds none. Returns the same `Result<String>` `pypackpack`'s backend does: `uv`'s own
     * combined stdout/stderr on success, or the failure it hit -- including a failed `initProject`,
     * which short-circuits before `addDependencies` is ever attempted.
     */
    suspend fun install(
        packageName: String,
        workingDir: File,
    ): Result<String> {
        backend.initialize()

        val existingRoot = findProjectRoot(workingDir)
        if (existingRoot == null) {
            // `--bare` matches what `pypackpack init` itself does (`docs/SPEC.md` "Project
            // creation"): only `pyproject.toml` is generated by `uv`, nothing else assumed.
            val initResult = backend.initProject(path = null, extraArgs = mapOf("bare" to ""), workingDir = workingDir)
            if (initResult.isFailure) return initResult
        }

        return backend.addDependencies(
            packageName = null,
            dependencies = listOf(packageName),
            extraArgs = null,
            workingDir = existingRoot ?: workingDir,
        )
    }
}

/** Synchronous entry point for callers (the CLI, tests) that are not already inside a coroutine. */
fun installBlocking(
    packageName: String,
    workingDir: File,
    installer: Installer = Installer(),
): Result<String> = runBlocking { installer.install(packageName, workingDir) }
